name: Publish Docker image

on:
  push:
    branches:
      - master
      - np-add-ga-workflow

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: nikitosing/red-blue-battle-master
      
      - name: Build and push setup Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/setup/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:setup
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push celery Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/celery/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:celery
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push celerybeat Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/celerybeat/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:celerybeat
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push flower Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/flower/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:flower
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push api Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/api/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:api
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push flag_receiver Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/flag_receiver/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:flag_receiver
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/frontend/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:frontend
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push nginx Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: docker_cfg/nginx/Dockerfile
          push: true
          tags: nikitosing/red-blue-battle-master:nginx
          labels: ${{ steps.meta.outputs.labels }}